version: '3'
services:
#  backend:
#    build: ./spring
#    container_name: goruna_backend
#    ports:
#      - "8100:8080"
#    depends_on:
#      - mysql

  mysql:
    image: mysql:latest
    container_name: mysqldb_goruna
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_goruna
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8091:80"
    depends_on:
      - mysql
    networks:
      - springboot-network

volumes:
  db_data:

networks:
  springboot-network:
    driver: bridge
