services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_goruna
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_goruna
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8091:80"
    networks:
      - springboot-network

volumes:
  db_data:

networks:
  springboot-network:
    driver: bridge