# ?? ?? ??
server:
  port: 8100
  servlet:
    encoding:
      charset: UTF-8

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha # ??? ??? ?? ??? ??
    operations-sorter: method # ??? ??? ??
    doc-expansion : none # Swagger ????? ?? ?? ??? ??